####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-simulators
Description: Simulators and utilities for automatic differentiation
Version: 2024.04-pre
Label: 2024.04-pre
Maintainer: atgeirr@sintef.no
MaintainerName: Atgeirr F. Rasmussen
Url: http://opm-project.org
Depends: dune-istl (>= 2.7) opm-common opm-grid opm-models
