#!/bin/bash

PYTHON_BINARY="$1"
PYTHON_PATH="$2"
PYTHON_SCRIPT="$3"
REFERENCE_DATA_PATH="$4"
OUTPUT_DATA_PATH="$5"
DECK_NAME="$6"
REL_TOL="$7"
ABS_TOL="$8"
EXE_NAME="$9"
TEST_DIR="${10}"
TEST_ARGS="${@:11:100}"

cd $TEST_DIR
$EXE_NAME $TEST_ARGS
PYTHONPATH="$2" $PYTHON_BINARY $PYTHON_SCRIPT $REFERENCE_DATA_PATH $OUTPUT_DATA_PATH $DECK_NAME $REL_TOL $ABS_TOL
